[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { workspace = true }
solver = { path = "../../lib/solver" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }