[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
parachain-client = { path = "../../lib/parachain-client" }
solver = { path = "../../lib/solver" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
uuid = { workspace = true , features = ["serde", "v4"], default-features = false }