[workspace]

members = [
    "bin/server",
    "lib/solver",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
futures = "0.3"
good_lp = "1" 
serde = "1" 
serde_json = "1" 
tokio = "1"
uuid = "1" 